// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWxb7WMIg92UxC4kyRv8fVS337XT1o31s',
    appId: '1:184626401841:web:134ddb3dfd1ee60c52fb10',
    messagingSenderId: '184626401841',
    projectId: 'book-list-2ef47',
    authDomain: 'book-list-2ef47.firebaseapp.com',
    databaseURL: 'https://book-list-2ef47-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'book-list-2ef47.appspot.com',
    measurementId: 'G-BGFKQM7VXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE_rLLNIj3wmwcvhxp8z2FAk20HDSxFyk',
    appId: '1:184626401841:android:ac83feaa15da361652fb10',
    messagingSenderId: '184626401841',
    projectId: 'book-list-2ef47',
    databaseURL: 'https://book-list-2ef47-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'book-list-2ef47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQpTWGrmti9iduJTRSeDLbEUqjp-Q53yE',
    appId: '1:184626401841:ios:f11bc67de47af2da52fb10',
    messagingSenderId: '184626401841',
    projectId: 'book-list-2ef47',
    databaseURL: 'https://book-list-2ef47-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'book-list-2ef47.appspot.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQpTWGrmti9iduJTRSeDLbEUqjp-Q53yE',
    appId: '1:184626401841:ios:f11bc67de47af2da52fb10',
    messagingSenderId: '184626401841',
    projectId: 'book-list-2ef47',
    databaseURL: 'https://book-list-2ef47-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'book-list-2ef47.appspot.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWxb7WMIg92UxC4kyRv8fVS337XT1o31s',
    appId: '1:184626401841:web:2c178f2f118adce052fb10',
    messagingSenderId: '184626401841',
    projectId: 'book-list-2ef47',
    authDomain: 'book-list-2ef47.firebaseapp.com',
    databaseURL: 'https://book-list-2ef47-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'book-list-2ef47.appspot.com',
    measurementId: 'G-WCZLLLB8NH',
  );
}
